version: "3"

services:
  # app:
  #   image: "101624687637.dkr.ecr.us-west-2.amazonaws.com/bespin:local"
  #   depends_on:
  #     - redis
  #     - db
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NODE_PATH: "/bin"
  #     NODE_OPTIONS: "--enable-source-maps"
  #     REDIS_HOST: "redis"
  #     MYSQL_HOST: "db"
  #     MYSQL_PORT: "3306"
  db:
    image: "mysql:8"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=bespin
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
  redis:
    image: "redis:5"
    ports:
      - "6379:6379"
